### ISSUE TITLE
搭建trojan和trojan-go谷歌云提示挖矿被封

### ISSUE THREAD

**Issue by XZXZZZ** [proxysu/ProxySU#37]
用两个不同的新的谷歌云vps搭了trojan和trojan-go，均提示警告挖矿而被封。请问怎么回事，有解决的方法吗？

**Comment by XZXZZZ** [comment]
警告如下：
概要
由于挖掘加密货币（挖矿），与您的项目 My First Project (id: outstanding-pen-xxxxx) 关联的资源因违反我们的免费试用服务条款而被暂停。

 
详细信息
受影响的项目/虚拟机：My First Project (id: outstanding-pen-xxxxxx)/

说明：因从虚拟机 挖掘加密货币（挖矿）而违反了我们的免费试用服务条款，进而导致虚拟机实例被暂停。

时间范围：从 2020-10-11 05:51 到 2020-10-11 05:58（美国太平洋时间）

**Comment by XZXZZZ** [comment]
> 伪装成静态网页+大流量+CPU大量占用与挖矿的行为很相似，谷歌云误判，你自己写申诉信，不行就不要用谷歌云

请问申诉内容该怎么写，没写过，不懂。

**Comment by SekiBetu** [comment]
I am sorry to hear that your development workflow has been delayed due to Cryptomining falsely being flagged on your project.

In our documentation on Policy violations FAQ [1], there is a section on projects under Suspension status.

In this section, it explains that in the example scenario of Cryptomining, it is very often tied to fraud, where malicious users use compromised account credentials to mine for cryptocurrency. 

Because of the high likelihood that such fraudulent activity would impact other users, we require additional verification [2] for these reasons. 

Typically, you will see a suspension in the Cloud Console and be required to submit an appeal. If you are an established customer or have a verified account, you will be notified to ensure the activity is intended, but will not be suspended. Use of blockchain is specifically excluded from this policy.

Furthermore, since you are not using your GCP project for Cryptomining, the next step would be to start an appeal process for your project, you can follow this documentation [3] on how to do so.

I hope this helps!

[1]Policy violations FAQ > Suspension > Why is my project suspended?:
https://support.google.com/cloud/answer/7002354#suspension 
[2]Additional verification:
https://cloud.google.com/billing/docs/how-to/invoiced-billing 
[3]Policy violations FAQ > My project has received a warning. What should I do now?:
https://support.google.com/cloud/answer/7002354?hl=en#warning-to-do

这是谷歌论坛一位工作人员回复被误封的人的内容，你看得懂就按照里面的要求去写信，看不懂就不要用谷歌云了，这玩意你只能和官方周旋，没有人能帮你

**Comment by XZXZZZ** [comment]
> I am sorry to hear that your development workflow has been delayed due to Cryptomining falsely being flagged on your project.
> 
> In our documentation on Policy violations FAQ [1], there is a section on projects under Suspension status.
> 
> In this section, it explains that in the example scenario of Cryptomining, it is very often tied to fraud, where malicious users use compromised account credentials to mine for cryptocurrency.
> 
> Because of the high likelihood that such fraudulent activity would impact other users, we require additional verification [2] for these reasons.
> 
> Typically, you will see a suspension in the Cloud Console and be required to submit an appeal. If you are an established customer or have a verified account, you will be notified to ensure the activity is intended, but will not be suspended. Use of blockchain is specifically excluded from this policy.
> 
> Furthermore, since you are not using your GCP project for Cryptomining, the next step would be to start an appeal process for your project, you can follow this documentation [3] on how to do so.
> 
> I hope this helps!
> 
> [1]Policy violations FAQ > Suspension > Why is my project suspended?:
> https://support.google.com/cloud/answer/7002354#suspension
> [2]Additional verification:
> https://cloud.google.com/billing/docs/how-to/invoiced-billing
> [3]Policy violations FAQ > My project has received a warning. What should I do now?:
> https://support.google.com/cloud/answer/7002354?hl=en#warning-to-do
> 
> 这是谷歌论坛一位工作人员回复被误封的人的内容，你看得懂就按照里面的要求去写信，看不懂就不要用谷歌云了，这玩意你只能和官方周旋，没有人能帮你

除了搬瓦工还有别的vps可以推荐一下吗？大神

**Comment by SekiBetu** [comment]
> > I am sorry to hear that your development workflow has been delayed due to Cryptomining falsely being flagged on your project.
> > In our documentation on Policy violations FAQ [1], there is a section on projects under Suspension status.
> > In this section, it explains that in the example scenario of Cryptomining, it is very often tied to fraud, where malicious users use compromised account credentials to mine for cryptocurrency.
> > Because of the high likelihood that such fraudulent activity would impact other users, we require additional verification [2] for these reasons.
> > Typically, you will see a suspension in the Cloud Console and be required to submit an appeal. If you are an established customer or have a verified account, you will be notified to ensure the activity is intended, but will not be suspended. Use of blockchain is specifically excluded from this policy.
> > Furthermore, since you are not using your GCP project for Cryptomining, the next step would be to start an appeal process for your project, you can follow this documentation [3] on how to do so.
> > I hope this helps!
> > [1]Policy violations FAQ > Suspension > Why is my project suspended?:
> > [support.google.com/cloud/answer/7002354#suspension](https://support.google.com/cloud/answer/7002354#suspension)
> > [2]Additional verification:
> > [cloud.google.com/billing/docs/how-to/invoiced-billing](https://cloud.google.com/billing/docs/how-to/invoiced-billing)
> > [3]Policy violations FAQ > My project has received a warning. What should I do now?:
> > [support.google.com/cloud/answer/7002354?hl=en#warning-to-do](https://support.google.com/cloud/answer/7002354?hl=en#warning-to-do)
> > 这是谷歌论坛一位工作人员回复被误封的人的内容，你看得懂就按照里面的要求去写信，看不懂就不要用谷歌云了，这玩意你只能和官方周旋，没有人能帮你
> 
> 除了谷歌云还有别的vps可以推荐一下吗？大神

zhujiceping.com

**Comment by shuishou4184** [comment]
我也这样，是不是因为打开了多路复用

**Comment by proxysu** [comment]
这个可能与谷歌云的一些限制有关系。

**Comment by rmqz** [comment]
先排除弱口令被扫
